# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: go:test
    silent: true

  go:test:
    desc: Run go tests with coverage and race detector
    sources:
      - "./**/*_test.go"
    cmds:
      - set -o pipefail && go test -cover -race ./... -json | gotestfmt

  go:tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  go:web:run:
    desc: Run dev web server
    watch: true
    sources:
      - "./client/web/**/*.*"
    generates:
      - "./bin/web"
    cmds:
      - go build -o ./bin/web ./client/web/main.go
      - ./bin/web
